name       : source-code-pro
version    : 2.030
release    : 2
source     :
    - https://github.com/adobe-fonts/source-code-pro/archive/2.030R-ro/1.050R-it.tar.gz : a4e4dd59b8e0a436b934f0f612c2e91b5932910c6d1c3b7d1a5a9f389c86302b
license    : SIL-1.1
component  : desktop.font
summary    : Source Code Pro Font Set
description: |
    Source Code Pro Font Set
install    : |
    mkdir -p %installroot%/usr/share/fonts/truetype/source-code-pro
    mkdir -p %installroot%/usr/share/doc/source-code-pro
    install -m 0644 TTF/*.ttf %installroot%/usr/share/fonts/truetype/source-code-pro/
    install -m 0644 LICENSE.txt %installroot%/usr/share/doc/source-code-pro/
