name       : source-code-pro
version    : 1.017
release    : 1
source     :
    - https://github.com/adobe-fonts/source-code-pro/archive/1.017R.tar.gz : 595aa593778beded801c12975f30ff1e78516654729afd2cfd8609121c50040f
license    : SIL-1.1
summary    : Source Code Pro Font Set
description: |
    Source Code Pro Font Set
install    : |
    mkdir -p %installroot%/usr/share/fonts/truetype/source-code-pro
    mkdir -p %installroot%/usr/share/doc/source-code-pro
    install -m 0644 TTF/*.ttf %installroot%/usr/share/fonts/truetype/source-code-pro/
    install -m 0644 LICENSE.txt %installroot%/usr/share/doc/source-code-pro/
